name: Download YouTube Video

on:
  workflow_dispatch:
    inputs:
      url:
        description: "YouTube URL"
        required: true

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg curl python3 python3-pip
          sudo pip install -U yt-dlp

      - name: Save cookies
        run: echo "${{ secrets.YT_COOKIES }}" > cookies.txt

      - name: Normalize URL
        run: |
          URL="${{ github.event.inputs.url }}"
          NORMALIZED=$(echo "$URL" | sed 's/shorts\//watch?v=/')
          echo "VIDEO_URL=$NORMALIZED" >> $GITHUB_ENV

      - name: Download video
        run: |
          mkdir downloads
          yt-dlp \
            --cookies cookies.txt \
            --extractor-args "youtube:player_client=android" \
            --force-ipv4 \
            -f "bv*+ba/b/best" \
            -o "downloads/%(title)s.%(ext)s" \
            "$VIDEO_URL"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: video
          path: downloads/
