name: Download YouTube Video

on:
  workflow_dispatch:
    inputs:
      url:
        description: "YouTube URL"
        required: true

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg curl
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod +x /usr/local/bin/yt-dlp

      - name: Install Node (fix JS warning)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Save cookies
        run: echo "${{ secrets.YT_COOKIES }}" > cookies.txt

      - name: Download video
        run: |
          mkdir downloads
          yt-dlp --cookies cookies.txt -o "downloads/%(title)s.%(ext)s" "${{ github.event.inputs.url }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: video
          path: downloads/
